image:
  name: technic93/e2xvfb:0.1
  run-as-user: 0

pipelines:
  default:
    - step:
        caches:
          - pip
        script:
          - uname -a
          - whoami
          - service apache2 start
          - Xvfb :99 -ac -screen 0 1280x720x16 &
          - export DISPLAY=:99
          - ps ax
          - pip install pep8
          - make
          - pep8 --ignore E126,E266,E226,W191,W293,E731 --max-line-length=119 src
          - python update-test.py
