version: 2
jobs:
  build:
    docker:
      - image: technic93/e2xvfb:0.1

    steps:
      - checkout

      - run:
          name: pip install
          command: pip install pep8

      - run:
          name: pep8
          command: |
            pep8 --version
            pep8 --ignore E126,E266,E226,W191,W293,E731 --max-line-length=119 src

      - run:
          name: build
          command: |
            apt-get update && apt-get install -y gettext rsync
            make
            make DEB=y

      - store_artifacts:
          path: packages
          destination: packages

      - run:
          name: test
          command: |
            ps ax
            python update-test.py
