version: 2

jobs:
  build:
    docker:
      - image: technic93/e2xvfb:0.1

    parameters:
      provider:
        type: string
        default: "all"

    environment:
      PROVIDER: << paramters.provider >>

    steps:
      - checkout

      - run:
          name: pep8
          command: |
            echo $PATH |tr ':' '\n'
            sudo pip install pep8
            pep8 --version
            pep8 --ignore E126,E266,E226,W191,W293,E731 --max-line-length=119 src

      - run:
          name: build
          command: |
            echo "PROVIDER=${PROVIDER}"
            apt-get update && apt-get install -y gettext rsync
            make
            make DEB=y

      - persist_to_workspace:
          root: packages
          paths:
            - *

      - store_artifacts:
          path: packages
          destination: packages

      - run:
          name: test update
          command: |
            uname -a
            whoami
            sudo mkdir -p /dev/input
            sudo service apache2 start
            sudo Xvfb :99 -ac -screen 0 1280x720x16 &
            export DISPLAY=:99
            ps ax
            sudo python update-test.py

  deploy:
    docker:
      - image: python:2.7.15
        # TODO:
    steps:
      - attach_workspace:
          at: packages
      - run:
        name: build and deploy
        command: |
          apt-get update && apt-get install -y rsync
          ls packages/

workflows:
  version: 2
  test-cbilling:
    jobs:
      - build:
          provider: cbilling
          filters:
            branches:
              only: cbilling

